application: craftersonline
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
# Show our from the distribution
- url: /css
  static_dir: public/css

# Show all our dist JS
- url: /js
  static_dir: public/js

# Show Images folder
- url: /img
  static_dir: public/img

# Setup Main Handler
- url: /.*
  script: crafting.main.app

error_handlers:
- file: views/errors/notfound.html

libraries:
- name: webapp2
  version: latest

- name: jinja2
  version: latest

